// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* driveSpeedController1;
	static SpeedController* driveSpeedController2;
	static SpeedController* driveSpeedController3;
	static SpeedController* driveSpeedController4;
	
	static Relay* pickupWheelsSpike1;
	static Relay* pickupWheelsSpike2;
	static DigitalInput* pickupWheelsLimitSwitch1;
	static DigitalInput* pickupWheelsLimitSwitch2;
	static DigitalInput* pickupWheelsLimitSwitch3;
	static DigitalInput* pickupWheelsLimitSwitch4;
	
	static SpeedController* pickupWheelsTopWheels;
	static SpeedController* ballistSpeedController1;
	static SpeedController* ballistSpeedController2;
	static SpeedController* ballistSpeedController3;
	static SpeedController* ballistSpeedController4;
	static DigitalInput* ballistLimitSwitch1;
	static Encoder* encoderQuadEncoder1;
	static Encoder* encoderQuadEncoder2;
	
	
	
	
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
	
	
	
};
#endif
