// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVE_H
#define DRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	int count1;
	float time1;
	int count2;
	float time2;
			
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* speedController1;
	SpeedController* speedController2;
	SpeedController* speedController3;
	SpeedController* speedController4;
	Encoder* quadEncoder1;
	Encoder* quadEncoder2;
	SpeedController* sucker;
	Relay* Arm1;
	Relay* Arm2;
	DigitalInput* armLimit1;
	DigitalInput* armLimit2;
	SpeedController* ballistMotor1;
	SpeedController* ballistMotor2;
	SpeedController* ballistMotor3;
	SpeedController* ballistMotor4;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Drive();
	void InitDefaultCommand();
	void SetSpeed1(Joystick*);
	void SetSpeed2(Joystick*);
	void Stop();
	void autoForward();
	void autoBackward();
	float dThrot;
	double count;
};

#endif
